"""Move is_active to user table

Revision ID: f995254e355b
Revises: 6c7b06df6c8b
Create Date: 2022-06-05 16:23:02.086840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f995254e355b'
down_revision = '6c7b06df6c8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
